{
	"schema_version": "1.6.0",
	"id": "CVE-2023-23456",
	"modified": "2024-09-18T03:23:03.690933Z",
	"published": "2023-01-12T19:15:24Z",
	"related": [
		"DLA-3991-1",
		"UBUNTU-CVE-2023-23456",
		"openSUSE-SU-2023:0088-1"
	],
	"details": "A heap-based buffer overflow issue was discovered in UPX in PackTmt::pack() in p_tmt.cpp file. The flow allows an attacker to cause a denial of service (abort) via a crafted file.",
	"severity": [
		{
			"type": "CVSS_V3",
			"score": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H"
		}
	],
	"affected": [
		{
			"package": {
				"ecosystem": "Debian:11",
				"name": "upx-ucl",
				"purl": "pkg:deb/debian/upx-ucl?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						}
					]
				}
			],
			"versions": [
				"3.96-2",
				"3.96-3",
				"4.2.2-1",
				"4.2.2-2",
				"4.2.2-3",
				"4.2.2-3~bpo12+1",
				"4.2.4-1"
			],
			"ecosystem_specific": {
				"urgency": "not yet assigned"
			},
			"database_specific": {
				"source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2023-23456.json"
			}
		},
		{
			"package": {
				"ecosystem": "Debian:13",
				"name": "upx-ucl",
				"purl": "pkg:deb/debian/upx-ucl?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "4.2.2-1"
						}
					]
				}
			],
			"versions": [
				"1.20-2",
				"1.24-2",
				"1.25-3",
				"1.25-4",
				"1.25-5",
				"2.00-1",
				"2.01-1",
				"2.03-1",
				"2.03-2",
				"2.03-3",
				"3.00-1",
				"3.00-2",
				"3.01-1",
				"3.01-2",
				"3.01-2.1",
				"3.01-3",
				"3.02-1",
				"3.02-2",
				"3.03-1",
				"3.03-2",
				"3.03-3",
				"3.04-1",
				"3.05-1",
				"3.07-1",
				"3.07-2",
				"3.07-3",
				"3.07-4",
				"3.08-1",
				"3.08-2",
				"3.09-1",
				"3.09-2",
				"3.91-1",
				"3.91-2",
				"3.91-3",
				"3.91-4",
				"3.93-1",
				"3.94+git20170809-1",
				"3.94+git20170810-1",
				"3.94+git20171222-1",
				"3.94-1",
				"3.94-2",
				"3.94-3",
				"3.94-4",
				"3.94-5",
				"3.95-1",
				"3.95-2",
				"3.95~git20180805-1",
				"3.96-1",
				"3.96-2",
				"3.96-3"
			],
			"ecosystem_specific": {
				"urgency": "not yet assigned"
			},
			"database_specific": {
				"source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2023-23456.json"
			}
		},
		{
			"package": {},
			"ranges": [
				{
					"type": "GIT",
					"repo": "https://github.com/upx/upx",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "510505a85cbe45e51fbd470f1aa8b02157c429d4"
						}
					]
				}
			],
			"versions": [
				"v1.10",
				"v1.11",
				"v1.90",
				"v1.91",
				"v1.92",
				"v1.93",
				"v1.94",
				"v1.95",
				"v1.96",
				"v2.00",
				"v2.01",
				"v2.90",
				"v2.91",
				"v2.92",
				"v2.93",
				"v3.00",
				"v3.01",
				"v3.02",
				"v3.03",
				"v3.04",
				"v3.05",
				"v3.06",
				"v3.07",
				"v3.08",
				"v3.09",
				"v3.91",
				"v3.92",
				"v3.93",
				"v3.94",
				"v3.95",
				"v3.96",
				"v3.99",
				"v4.0.0",
				"v4.0.1"
			],
			"database_specific": {
				"source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2023-23456.json"
			}
		}
	],
	"references": [
		{
			"type": "REPORT",
			"url": "https://github.com/upx/upx/issues/632"
		},
		{
			"type": "FIX",
			"url": "https://github.com/upx/upx/commit/510505a85cbe45e51fbd470f1aa8b02157c429d4"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2160381"
		},
		{
			"type": "WEB",
			"url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/EL3BVKIGG3SH6I3KPOYQAWCBD4UMPOPI/"
		},
		{
			"type": "WEB",
			"url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/TGEP3FBNRZXGLIA2B2ICMB32JVMPREFZ/"
		},
		{
			"type": "ADVISORY",
			"url": "https://security-tracker.debian.org/tracker/CVE-2023-23456"
		}
	]
}
