{
	"schema_version": "1.6.0",
	"id": "CVE-2021-3514",
	"modified": "2024-09-18T01:00:20Z",
	"published": "2021-05-28T15:15:09Z",
	"related": [
		"DLA-3399-1",
		"RLSA-2021:2595",
		"SUSE-SU-2021:1878-1",
		"USN-5231-1",
		"openSUSE-SU-2021:0868-1"
	],
	"details": "When using a sync_repl client in 389-ds-base, an authenticated attacker can cause a NULL pointer dereference using a specially crafted query, causing a crash.",
	"severity": [
		{
			"type": "CVSS_V3",
			"score": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
		}
	],
	"affected": [
		{
			"package": {
				"ecosystem": "Debian:11",
				"name": "389-ds-base",
				"purl": "pkg:deb/debian/389-ds-base?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "1.4.4.11-2"
						}
					]
				}
			],
			"ecosystem_specific": {
				"urgency": "not yet assigned"
			},
			"database_specific": {
				"source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2021-3514.json"
			}
		},
		{
			"package": {
				"ecosystem": "Debian:12",
				"name": "389-ds-base",
				"purl": "pkg:deb/debian/389-ds-base?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "1.4.4.11-2"
						}
					]
				}
			],
			"ecosystem_specific": {
				"urgency": "not yet assigned"
			},
			"database_specific": {
				"source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2021-3514.json"
			}
		},
		{
			"package": {
				"ecosystem": "Debian:13",
				"name": "389-ds-base",
				"purl": "pkg:deb/debian/389-ds-base?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "1.4.4.11-2"
						}
					]
				}
			],
			"ecosystem_specific": {
				"urgency": "not yet assigned"
			},
			"database_specific": {
				"source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2021-3514.json"
			}
		}
	],
	"references": [
		{
			"type": "REPORT",
			"url": "https://github.com/389ds/389-ds-base/issues/4711"
		},
		{
			"type": "WEB",
			"url": "https://lists.debian.org/debian-lts-announce/2023/04/msg00026.html"
		},
		{
			"type": "ADVISORY",
			"url": "https://security-tracker.debian.org/tracker/CVE-2021-3514"
		}
	]
}
