{
	"schema_version": "1.6.0",
	"id": "CVE-2019-9947",
	"modified": "2024-09-18T01:00:22Z",
	"published": "2019-03-23T18:29:02Z",
	"aliases": [
		"PSF-2019-11"
	],
	"related": [
		"ALSA-2019:3335",
		"DLA-1834-1",
		"DLA-1835-1",
		"DLA-2280-1",
		"DLA-2337-1",
		"RHSA-2019:1260",
		"RHSA-2019:2030",
		"RHSA-2019:3335",
		"RHSA-2019:3520",
		"RHSA-2019:3725",
		"RHSA-2020:1268",
		"RHSA-2020:1346",
		"RHSA-2020:1462",
		"RLSA-2019:3335",
		"SUSE-FU-2022:0444-1",
		"SUSE-FU-2022:0445-1",
		"SUSE-RU-2020:0775-1",
		"SUSE-SU-2019:1352-1",
		"SUSE-SU-2019:1352-2",
		"SUSE-SU-2019:14246-1",
		"SUSE-SU-2019:2743-1",
		"SUSE-SU-2020:0114-1",
		"SUSE-SU-2020:0234-1",
		"SUSE-SU-2020:0302-1",
		"SUSE-SU-2020:2699-1",
		"UBUNTU-CVE-2019-9947",
		"USN-4127-1",
		"USN-4127-2",
		"USN-6891-1",
		"openSUSE-SU-2019:2389-1",
		"openSUSE-SU-2019:2393-1",
		"openSUSE-SU-2020:0086-1",
		"openSUSE-SU-2024:11202-1",
		"openSUSE-SU-2024:11283-1",
		"openSUSE-SU-2024:11284-1",
		"openSUSE-SU-2024:11285-1",
		"openSUSE-SU-2024:11286-1",
		"openSUSE-SU-2024:12089-1",
		"openSUSE-SU-2024:12910-1",
		"openSUSE-SU-2024:14109-1"
	],
	"details": "An issue was discovered in urllib2 in Python 2.x through 2.7.16 and urllib in Python 3.x through 3.7.3. CRLF injection is possible if the attacker controls a url parameter, as demonstrated by the first argument to urllib.request.urlopen with \\r\\n (specifically in the path component of a URL that lacks a ? character) followed by an HTTP header or a Redis command. This is similar to the CVE-2019-9740 query string issue. This is fixed in: v2.7.17, v2.7.17rc1, v2.7.18, v2.7.18rc1; v3.5.10, v3.5.10rc1, v3.5.8, v3.5.8rc1, v3.5.8rc2, v3.5.9; v3.6.10, v3.6.10rc1, v3.6.11, v3.6.11rc1, v3.6.12, v3.6.9, v3.6.9rc1; v3.7.4, v3.7.4rc1, v3.7.4rc2, v3.7.5, v3.7.5rc1, v3.7.6, v3.7.6rc1, v3.7.7, v3.7.7rc1, v3.7.8, v3.7.8rc1, v3.7.9.",
	"severity": [
		{
			"type": "CVSS_V3",
			"score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N"
		}
	],
	"affected": [
		{
			"package": {
				"ecosystem": "Debian:11",
				"name": "python2.7",
				"purl": "pkg:deb/debian/python2.7?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "2.7.16-3"
						}
					]
				}
			],
			"ecosystem_specific": {
				"urgency": "not yet assigned"
			},
			"database_specific": {
				"source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2019-9947.json"
			}
		},
		{
			"package": {},
			"ranges": [
				{
					"type": "GIT",
					"repo": "https://github.com/python/cpython",
					"events": [
						{
							"introduced": "2e789a1f1d84b343a996e8654590703b5fbdd441"
						},
						{
							"fixed": "ac39a516017c80993309f803441c8ee97c44838e"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2019-9947.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://access.redhat.com/errata/RHSA-2019:1260"
		},
		{
			"type": "ADVISORY",
			"url": "https://access.redhat.com/errata/RHSA-2019:2030"
		},
		{
			"type": "ADVISORY",
			"url": "https://access.redhat.com/errata/RHSA-2019:3335"
		},
		{
			"type": "ADVISORY",
			"url": "https://access.redhat.com/errata/RHSA-2019:3520"
		},
		{
			"type": "ADVISORY",
			"url": "https://access.redhat.com/errata/RHSA-2019:3725"
		},
		{
			"type": "REPORT",
			"url": "https://bugs.python.org/issue35906"
		},
		{
			"type": "ADVISORY",
			"url": "https://security.gentoo.org/glsa/202003-26"
		},
		{
			"type": "ADVISORY",
			"url": "https://security.netapp.com/advisory/ntap-20190404-0004/"
		},
		{
			"type": "WEB",
			"url": "http://lists.opensuse.org/opensuse-security-announce/2019-10/msg00062.html"
		},
		{
			"type": "WEB",
			"url": "http://lists.opensuse.org/opensuse-security-announce/2019-10/msg00063.html"
		},
		{
			"type": "WEB",
			"url": "http://lists.opensuse.org/opensuse-security-announce/2020-01/msg00040.html"
		},
		{
			"type": "WEB",
			"url": "http://www.openwall.com/lists/oss-security/2021/02/04/2"
		},
		{
			"type": "WEB",
			"url": "https://lists.debian.org/debian-lts-announce/2019/06/msg00022.html"
		},
		{
			"type": "WEB",
			"url": "https://lists.debian.org/debian-lts-announce/2019/06/msg00023.html"
		},
		{
			"type": "WEB",
			"url": "https://lists.debian.org/debian-lts-announce/2019/06/msg00026.html"
		},
		{
			"type": "WEB",
			"url": "https://lists.debian.org/debian-lts-announce/2020/07/msg00011.html"
		},
		{
			"type": "WEB",
			"url": "https://lists.debian.org/debian-lts-announce/2020/08/msg00034.html"
		},
		{
			"type": "WEB",
			"url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/JMWSKTNOHSUOT3L25QFJAVCFYZX46FYK/"
		},
		{
			"type": "WEB",
			"url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/JXASHCDD4PQFKTMKQN4YOP5ZH366ABN4/"
		},
		{
			"type": "WEB",
			"url": "https://usn.ubuntu.com/4127-1/"
		},
		{
			"type": "WEB",
			"url": "https://usn.ubuntu.com/4127-2/"
		},
		{
			"type": "ADVISORY",
			"url": "https://security-tracker.debian.org/tracker/CVE-2019-9947"
		}
	]
}
