{
	"schema_version": "1.6.0",
	"id": "CVE-2018-16881",
	"modified": "2024-09-18T01:00:22Z",
	"published": "2019-01-25T18:29:00Z",
	"related": [
		"DLA-3016-1",
		"RHBA-2019:2501",
		"RHSA-2019:2110",
		"RHSA-2019:2437",
		"RHSA-2019:2439",
		"SUSE-SU-2019:0209-1",
		"UBUNTU-CVE-2018-16881",
		"USN-5419-1"
	],
	"details": "A denial of service vulnerability was found in rsyslog in the imptcp module. An attacker could send a specially crafted message to the imptcp socket, which would cause rsyslog to crash. Versions before 8.27.0 are vulnerable.",
	"severity": [
		{
			"type": "CVSS_V3",
			"score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
		}
	],
	"affected": [
		{
			"package": {
				"ecosystem": "Debian:11",
				"name": "rsyslog",
				"purl": "pkg:deb/debian/rsyslog?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "8.27.0-2"
						}
					]
				}
			],
			"ecosystem_specific": {
				"urgency": "not yet assigned"
			},
			"database_specific": {
				"source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2018-16881.json"
			}
		},
		{
			"package": {
				"ecosystem": "Debian:12",
				"name": "rsyslog",
				"purl": "pkg:deb/debian/rsyslog?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "8.27.0-2"
						}
					]
				}
			],
			"ecosystem_specific": {
				"urgency": "not yet assigned"
			},
			"database_specific": {
				"source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2018-16881.json"
			}
		},
		{
			"package": {
				"ecosystem": "Debian:13",
				"name": "rsyslog",
				"purl": "pkg:deb/debian/rsyslog?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "8.27.0-2"
						}
					]
				}
			],
			"ecosystem_specific": {
				"urgency": "not yet assigned"
			},
			"database_specific": {
				"source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2018-16881.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://access.redhat.com/errata/RHBA-2019:2501"
		},
		{
			"type": "ADVISORY",
			"url": "https://access.redhat.com/errata/RHSA-2019:2110"
		},
		{
			"type": "ADVISORY",
			"url": "https://access.redhat.com/errata/RHSA-2019:2437"
		},
		{
			"type": "ADVISORY",
			"url": "https://access.redhat.com/errata/RHSA-2019:2439"
		},
		{
			"type": "WEB",
			"url": "https://lists.debian.org/debian-lts-announce/2022/05/msg00028.html"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-16881"
		},
		{
			"type": "ADVISORY",
			"url": "https://security-tracker.debian.org/tracker/CVE-2018-16881"
		}
	]
}
