{
	"schema_version": "1.6.0",
	"id": "DLA-3932-1",
	"modified": "2024-10-22T14:09:12.798740Z",
	"published": "2024-10-22T00:00:00Z",
	"related": [
		"CVE-2024-9774"
	],
	"summary": "python-sql - security update",
	"affected": [
		{
			"package": {
				"ecosystem": "Debian:11",
				"name": "python-sql",
				"purl": "pkg:deb/debian/python-sql?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "1.2.1-1+deb11u1"
						}
					]
				}
			],
			"versions": [
				"1.2.1-1"
			],
			"database_specific": {
				"source": "https://storage.googleapis.com/debian-osv/dla-osv/DLA-3932-1.json"
			}
		}
	]
}
