{
	"schema_version": "1.6.0",
	"id": "CVE-2021-3753",
	"modified": "2024-09-18T03:15:33.182148Z",
	"published": "2022-02-16T19:15:08Z",
	"aliases": [
		"A-222023207",
		"PUB-A-222023207"
	],
	"related": [
		"DLA-2785-1",
		"DLA-2843-1",
		"DSA-4978-1",
		"RLSA-2024:2950",
		"RLSA-2024:3138",
		"SUSE-SU-2021:3177-1",
		"SUSE-SU-2021:3178-1",
		"SUSE-SU-2021:3179-1",
		"SUSE-SU-2021:3192-1",
		"SUSE-SU-2021:3205-1",
		"SUSE-SU-2021:3205-2",
		"SUSE-SU-2021:3206-1",
		"SUSE-SU-2021:3207-1",
		"SUSE-SU-2021:3217-1",
		"SUSE-SU-2021:3415-1",
		"SUSE-SU-2021:3876-1",
		"SUSE-SU-2021:3929-1",
		"SUSE-SU-2021:3935-1",
		"SUSE-SU-2021:3969-1",
		"SUSE-SU-2021:3972-1",
		"SUSE-SU-2022:14905-1",
		"USN-5113-1",
		"USN-5115-1",
		"USN-5117-1",
		"USN-5136-1",
		"USN-5137-1",
		"USN-5137-2",
		"USN-6221-1",
		"openSUSE-SU-2021:1271-1",
		"openSUSE-SU-2021:3179-1",
		"openSUSE-SU-2021:3205-1",
		"openSUSE-SU-2021:3876-1",
		"openSUSE-SU-2024:10728-1",
		"openSUSE-SU-2024:13704-1"
	],
	"details": "A race problem was seen in the vt_k_ioctl in drivers/tty/vt/vt_ioctl.c in the Linux kernel, which may cause an out of bounds read in vt as the write access to vc_mode is not protected by lock-in vt_ioctl (KDSETMDE). The highest threat from this vulnerability is to data confidentiality.",
	"severity": [
		{
			"type": "CVSS_V3",
			"score": "CVSS:3.1/AV:L/AC:H/PR:L/UI:N/S:U/C:H/I:N/A:N"
		}
	],
	"affected": [
		{
			"package": {
				"ecosystem": "Debian:11",
				"name": "linux",
				"purl": "pkg:deb/debian/linux?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "5.10.46-5"
						}
					]
				}
			],
			"versions": [
				"5.10.46-4"
			],
			"ecosystem_specific": {
				"urgency": "not yet assigned"
			},
			"database_specific": {
				"source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2021-3753.json"
			}
		},
		{
			"package": {
				"ecosystem": "Debian:12",
				"name": "linux",
				"purl": "pkg:deb/debian/linux?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "5.14.6-1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"urgency": "not yet assigned"
			},
			"database_specific": {
				"source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2021-3753.json"
			}
		},
		{
			"package": {
				"ecosystem": "Debian:13",
				"name": "linux",
				"purl": "pkg:deb/debian/linux?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "5.14.6-1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"urgency": "not yet assigned"
			},
			"database_specific": {
				"source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2021-3753.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://security.netapp.com/advisory/ntap-20221028-0003/"
		},
		{
			"type": "WEB",
			"url": "https://www.openwall.com/lists/oss-security/2021/09/01/4"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1999589"
		},
		{
			"type": "FIX",
			"url": "https://github.com/torvalds/linux/commit/2287a51ba822384834dafc1c798453375d1107c7"
		},
		{
			"type": "ADVISORY",
			"url": "https://security-tracker.debian.org/tracker/CVE-2021-3753"
		}
	]
}
