{
	"schema_version": "1.6.0",
	"id": "CVE-2020-36599",
	"modified": "2024-09-18T03:11:09.868358Z",
	"published": "2022-08-18T23:15:08Z",
	"aliases": [
		"GHSA-pm55-qfxr-h247"
	],
	"details": "lib/omniauth/failure_endpoint.rb in OmniAuth before 1.9.2 (and before 2.0) does not escape the message_key value.",
	"severity": [
		{
			"type": "CVSS_V3",
			"score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
		}
	],
	"affected": [
		{
			"package": {
				"ecosystem": "Debian:11",
				"name": "ruby-omniauth",
				"purl": "pkg:deb/debian/ruby-omniauth?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						}
					]
				}
			],
			"versions": [
				"1.9.1-1",
				"2.0.4-1",
				"2.0.4-1~exp1",
				"2.0.4-2",
				"2.1.0-1",
				"2.1.1-1"
			],
			"ecosystem_specific": {
				"urgency": "not yet assigned"
			},
			"database_specific": {
				"source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2020-36599.json"
			}
		},
		{
			"package": {
				"ecosystem": "Debian:12",
				"name": "ruby-omniauth",
				"purl": "pkg:deb/debian/ruby-omniauth?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "2.0.4-2"
						}
					]
				}
			],
			"ecosystem_specific": {
				"urgency": "not yet assigned"
			},
			"database_specific": {
				"source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2020-36599.json"
			}
		},
		{
			"package": {
				"ecosystem": "Debian:13",
				"name": "ruby-omniauth",
				"purl": "pkg:deb/debian/ruby-omniauth?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "2.0.4-2"
						}
					]
				}
			],
			"ecosystem_specific": {
				"urgency": "not yet assigned"
			},
			"database_specific": {
				"source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2020-36599.json"
			}
		},
		{
			"package": {},
			"ranges": [
				{
					"type": "GIT",
					"repo": "https://github.com/omniauth/omniauth",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "43a396f181ef7d0ed2ec8291c939c95e3ed3ff00"
						}
					]
				}
			],
			"versions": [
				"v0.0.1",
				"v0.0.3",
				"v0.0.4",
				"v0.1.1",
				"v0.1.3",
				"v0.1.4",
				"v0.1.5",
				"v0.1.6",
				"v0.2.0",
				"v0.2.0.beta1",
				"v0.2.0.beta2",
				"v0.2.0.beta4",
				"v0.2.0.beta5",
				"v0.2.1",
				"v0.2.2",
				"v0.2.3",
				"v0.2.4",
				"v0.2.5",
				"v0.2.6",
				"v0.3.0.rc1",
				"v0.3.0.rc2",
				"v0.3.0.rc3",
				"v1.0.0",
				"v1.0.0.beta1",
				"v1.0.0.pr1",
				"v1.0.0.pr2",
				"v1.0.0.rc1",
				"v1.0.0.rc2",
				"v1.0.1",
				"v1.0.2",
				"v1.0.3",
				"v1.1.0",
				"v1.1.1",
				"v1.1.2",
				"v1.1.3",
				"v1.1.4",
				"v1.2.0",
				"v1.2.1",
				"v1.2.2",
				"v1.3.0",
				"v1.3.1",
				"v1.3.2",
				"v1.4.0",
				"v1.4.1",
				"v1.4.2",
				"v1.4.3",
				"v1.5.0",
				"v1.6.0",
				"v1.6.1",
				"v1.7.0",
				"v1.7.1",
				"v1.8.0",
				"v1.8.1",
				"v1.9.0",
				"v1.9.1"
			],
			"database_specific": {
				"source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2020-36599.json"
			}
		}
	],
	"references": [
		{
			"type": "FIX",
			"url": "https://github.com/omniauth/omniauth/commit/43a396f181ef7d0ed2ec8291c939c95e3ed3ff00#diff-575abda9deb9b1a77bf534e898a923029b9a61e991d626db88dc6e8b34260aa2"
		},
		{
			"type": "WEB",
			"url": "https://rubygems.org/gems/omniauth/versions/1.9.2"
		},
		{
			"type": "ADVISORY",
			"url": "https://security-tracker.debian.org/tracker/CVE-2020-36599"
		}
	]
}
