{
	"schema_version": "1.6.0",
	"id": "DLA-4007-1",
	"modified": "2025-01-01T03:04:27.627991Z",
	"published": "2025-01-01T00:00:00Z",
	"related": [
		"CVE-2023-28370",
		"CVE-2024-52804"
	],
	"summary": "python-tornado - security update",
	"affected": [
		{
			"package": {
				"ecosystem": "Debian:11",
				"name": "python-tornado",
				"purl": "pkg:deb/debian/python-tornado?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "6.1.0-1+deb11u1"
						}
					]
				}
			],
			"versions": [
				"6.1.0-1"
			],
			"database_specific": {
				"source": "https://storage.googleapis.com/debian-osv/dla-osv/DLA-4007-1.json"
			}
		}
	]
}
