{
	"schema_version": "1.6.0",
	"id": "DLA-1889-1",
	"modified": "2024-01-09T20:31:50.110639Z",
	"published": "2019-08-17T00:00:00Z",
	"related": [
		"CVE-2018-20852"
	],
	"summary": "python3.4 - security update",
	"affected": [
		{
			"package": {
				"ecosystem": "Debian:8",
				"name": "python3.4",
				"purl": "pkg:deb/debian/python3.4?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "3.4.2-1+deb8u6"
						}
					]
				}
			],
			"versions": [
				"3.4.2-1",
				"3.4.2-1+deb8u1",
				"3.4.2-1+deb8u2",
				"3.4.2-1+deb8u3",
				"3.4.2-1+deb8u4",
				"3.4.2-1+deb8u5"
			],
			"database_specific": {
				"source": "https://storage.googleapis.com/debian-osv/dla-osv/DLA-1889-1.json"
			}
		}
	]
}
