{
	"schema_version": "1.6.0",
	"id": "DSA-3893-1",
	"modified": "2023-10-16T00:12:26.220444Z",
	"published": "2017-06-22T00:00:00Z",
	"related": [
		"CVE-2016-4000"
	],
	"summary": "jython - security update",
	"details": "\nAlvaro Munoz and Christian Schneider discovered that jython, an\nimplementation of the Python language seamlessly integrated with Java,\nis prone to arbitrary code execution triggered when sending a serialized\nfunction to the deserializer.\n\n\nFor the oldstable distribution (jessie), this problem has been fixed\nin version 2.5.3-3+deb8u1.\n\n\nFor the stable distribution (stretch), this problem has been fixed in\nversion 2.5.3-16+deb9u1.\n\n\nFor the unstable distribution (sid), this problem has been fixed in\nversion 2.5.3-17.\n\n\nWe recommend that you upgrade your jython packages.\n\n\n",
	"affected": [
		{
			"package": {
				"ecosystem": "Debian:8",
				"name": "jython",
				"purl": "pkg:deb/debian/jython?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "2.5.3-3+deb8u1"
						}
					]
				}
			],
			"versions": [
				"2.5.3-3"
			],
			"database_specific": {
				"source": "https://storage.googleapis.com/debian-osv/dsa-osv/DSA-3893-1.json"
			}
		},
		{
			"package": {
				"ecosystem": "Debian:9",
				"name": "jython",
				"purl": "pkg:deb/debian/jython?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "2.5.3-16+deb9u1"
						}
					]
				}
			],
			"versions": [
				"2.5.3-16"
			],
			"database_specific": {
				"source": "https://storage.googleapis.com/debian-osv/dsa-osv/DSA-3893-1.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://www.debian.org/security/2017/dsa-3893"
		}
	]
}
